apiVersion: apps/v1
kind: Deployment
metadata: 
  name: senior-app
spec:   
  replicas: 1
  selector: 
    matchLabels: 
      app: senior-app
  template:
    metadata:
      labels:
        app: senior-app
    spec:
      containers:
        - name: senior-app 
          image: senior-app:v1
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: SESSION_SECRET
              value: "secret$%^134"
            - name: DB_HOST
              value: "10.104.231.199"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "root"
            - name: DB_DATABASE
              value: "senior_db"
            - name: COOKIE_NAME
              value: "session"
            - name: RABBITMQ_URL
              value: "amqp://localhost"

